version: "3.8"

services:
    app:
        build: .
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: postgres:14
        environment:
            POSTGRES_DB: test
            POSTGRES_USER: test_plkh_user
            POSTGRES_PASSWORD: q3tJEcBng52n6JX7YX6iJBYXKJbkt8Hq
        ports:
            - "5432:5432"
